#!/usr/bin/env python3
import json
import argparse
import script
s = script.Script('deleteAgent')
s.parser.add_argument('agentId')
args = s.args()
print(json.dumps(s.run({
    'agent_id': args.agentId,
})['deleted']))
