#!/usr/bin/env python3
import json
import script
s = script.Script('deregisterMachine', 'principalKeyFile')
s.parser.add_argument('machineKey')
args = s.args()
print(json.dumps(s.run({
    'machine': args.machineKey,
})['deleted']))
