#!/usr/bin/env python3
import script
import json
s = script.Script('getCertificateRequests')
args = s.args()
for req in s.run({})['requests']:
    print(req['user'] + ((' ' + req['comment']) if req['comment'] else ''))
