#!/usr/bin/env python3
import script
s = script.Script('getCertificate', 'userKeyFile')
s.parser.add_argument('principal')
args = s.args()
print(s.run({
    'principal': args.principal,
})['certificate'] or '')
