#!/usr/bin/env python3
import argparse
import script
import json
s = script.Script('getCertificateRequests', 'principalKeyFile')
s.parser.add_argument('--json', action=argparse.BooleanOptionalAction)
args = s.args()
for req in s.run({})['requests']:
    if args.json:
        print(json.dumps(req))
    else:
        print(req['machine'] + ((' ' + req['comment']) if req['comment'] else ''))
