#!/usr/bin/env python3
import argparse
import script
import json
import base64
import urllib.parse
s = script.Script('invitePrincipal', 'adminKeyFile')
s.parser.add_argument('principal')
s.parser.add_argument('--expiry', type=int, default=86400)
s.parser.add_argument('--invitation-code-only', action=argparse.BooleanOptionalAction)
args = s.args()
invite_secret = s.run({
    'principal': args.principal,
    'expiry_seconds': args.expiry,
})['invite_secret']
if args.invitation_code_only:
    print(invite_secret)
else:
    print(args.serviceUrl + '#!' + urllib.parse.urlencode({
        'principal': args.principal,
        'secret': invite_secret,
    }))
    invitation = {
        'principal': args.principal,
        'serviceUrl': args.serviceUrl + '_/rpc',
        'invitationCode': invite_secret,
    }
    print('comleastfixedpointsshcertauth:invitation?' +
          base64.b64encode(json.dumps(invitation).encode('utf-8')).decode('utf-8'))
