#!/usr/bin/env python3
import argparse
import script
s = script.Script('inviteAgent')
s.parser.add_argument('agentId')
s.parser.add_argument('--expiry', type=int, default=86400)
s.parser.add_argument('--invitation-code-only', action=argparse.BooleanOptionalAction)
args = s.args()
invite_secret = s.run({
    'agent_id': args.agentId,
    'expiry_seconds': args.expiry,
})['invite_secret']
if args.invitation_code_only:
    print(invite_secret)
else:
    print(args.serviceUrl + 'invite.html#!' + invite_secret)
