#!/usr/bin/env python3
import script
s = script.Script('inviteAgent')
s.parser.add_argument('agentId')
s.parser.add_argument('--expiry', type=int, default=86400)
args = s.args()
print(s.run({
    'agent_id': args.agentId,
    'expiry_seconds': args.expiry,
})['invite_secret'])
