#!/usr/bin/env python3
import script
import argparse
import json
s = script.Script('listUsers', 'principalKeyFile')
s.parser.add_argument('--json', action=argparse.BooleanOptionalAction)
args = s.args()
if not args.json:
    print('comment\tcert_present\tregistration_time\trequest_time\tpub')
for u in s.run({})['users']:
    if args.json:
        print(json.dumps(u))
    else:
        print(f'{u["comment"]}\t{"Y" if u["certificate"] else "N"}\t{u["registration_time"] or ""}\t{u["request_time"] or ""}\t{u["user"]}')
