#!/usr/bin/env python3
import script
import json
s = script.Script('lookupRegistration', 'principalKeyFile')
s.parser.add_argument('rendezvousCode')
args = s.args()
res = s.run({
    'rendezvous_code': args.rendezvousCode,
})
if res['found']:
    print(res['user'] + ((' ' + res['comment']) if res['comment'] else ''))
