#!/usr/bin/env python3
import script
s = script.Script('registerLaptop')
s.parser.add_argument('agentId')
s.parser.add_argument('comment')
args = s.args()
print(s.run({
    'agent_id': args.agentId,
    'comment': args.comment,
})['temp_code'])
