#!/usr/bin/env python3
import script
s = script.Script('registerPrincipal', 'principalKeyFile')
s.parser.add_argument('inviteSecret')
args = s.args()
s.run({
    'invite_secret': args.inviteSecret,
})
