#!/usr/bin/env python3
import script

def defaultComment():
    import os
    import socket
    return os.getlogin() + '@' + socket.getfqdn()

s = script.Script('registerUser', 'userKeyFile')
s.parser.add_argument('principal')
s.parser.add_argument('comment', default=None, nargs='?')
args = s.args()
print(s.run({
    'principal': args.principal,
    'comment': args.comment or defaultComment(),
})['rendezvous_code'])
