#!/usr/bin/env python3
import script
s = script.Script('registerServer', None)
s.parser.add_argument('principal')
args = s.args()
print(s.run({
    'principal': args.principal,
})['principal_key'] or '')
