#!/usr/bin/env python3
import script
s = script.Script('registerServer', keyFileNeeded=False)
s.parser.add_argument('agentId')
args = s.args()
print(s.run({
    'agent_id': args.agentId,
})['agent'] or '')
