#!/usr/bin/env python3
import script
s = script.Script('setCertificate')
s.parser.add_argument('userKey')
s.parser.add_argument('certificate', default=None, nargs='?')
args = s.args()
s.run({
    'user': args.userKey,
    'certificate': None if args.certificate == '' else args.certificate,
})
