#!/usr/bin/env python3
import script
import json
s = script.Script('setUser', 'principalKeyFile')
s.parser.add_argument('userKey')
s.parser.add_argument('comment')
s.parser.add_argument('certificate', default='', nargs='?')
args = s.args()
s.run({
    'user': args.userKey,
    'comment': args.comment,
    'certificate': None if args.certificate == '' else args.certificate,
})
